namespace GUI
{
    partial class SanPham_form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SanPham_form));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuDataGridView_SanPham = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuTextBox_TenSP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton_DanhMuc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBox_Gia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBox_MoTa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDropdown_DanhMuc = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBox_SL = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton_ThemAnh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.openFileDialog_SanPham = new System.Windows.Forms.OpenFileDialog();
            this.bunifuPictureBox_SanPham = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView_SanPham)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox_SanPham)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuDataGridView_SanPham
            // 
            this.bunifuDataGridView_SanPham.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView_SanPham.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView_SanPham.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuDataGridView_SanPham.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView_SanPham.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView_SanPham.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView_SanPham.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView_SanPham.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridView_SanPham.ColumnHeadersHeight = 40;
            this.bunifuDataGridView_SanPham.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView_SanPham.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView_SanPham.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView_SanPham.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView_SanPham.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView_SanPham.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView_SanPham.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView_SanPham.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView_SanPham.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView_SanPham.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.CurrentTheme.Name = null;
            this.bunifuDataGridView_SanPham.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView_SanPham.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView_SanPham.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView_SanPham.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView_SanPham.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridView_SanPham.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView_SanPham.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView_SanPham.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView_SanPham.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView_SanPham.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView_SanPham.Location = new System.Drawing.Point(1, 0);
            this.bunifuDataGridView_SanPham.Name = "bunifuDataGridView_SanPham";
            this.bunifuDataGridView_SanPham.RowHeadersVisible = false;
            this.bunifuDataGridView_SanPham.RowTemplate.Height = 40;
            this.bunifuDataGridView_SanPham.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView_SanPham.Size = new System.Drawing.Size(446, 578);
            this.bunifuDataGridView_SanPham.TabIndex = 0;
            this.bunifuDataGridView_SanPham.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridView_SanPham.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView_SanPham_CellContentClick);
            // 
            // bunifuTextBox_TenSP
            // 
            this.bunifuTextBox_TenSP.AcceptsReturn = false;
            this.bunifuTextBox_TenSP.AcceptsTab = false;
            this.bunifuTextBox_TenSP.AnimationSpeed = 200;
            this.bunifuTextBox_TenSP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox_TenSP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox_TenSP.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox_TenSP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox_TenSP.BackgroundImage")));
            this.bunifuTextBox_TenSP.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox_TenSP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox_TenSP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox_TenSP.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox_TenSP.BorderRadius = 1;
            this.bunifuTextBox_TenSP.BorderThickness = 1;
            this.bunifuTextBox_TenSP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox_TenSP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_TenSP.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox_TenSP.DefaultText = "";
            this.bunifuTextBox_TenSP.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox_TenSP.HideSelection = true;
            this.bunifuTextBox_TenSP.IconLeft = null;
            this.bunifuTextBox_TenSP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_TenSP.IconPadding = 10;
            this.bunifuTextBox_TenSP.IconRight = null;
            this.bunifuTextBox_TenSP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_TenSP.Lines = new string[0];
            this.bunifuTextBox_TenSP.Location = new System.Drawing.Point(486, 28);
            this.bunifuTextBox_TenSP.MaxLength = 32767;
            this.bunifuTextBox_TenSP.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox_TenSP.Modified = false;
            this.bunifuTextBox_TenSP.Multiline = false;
            this.bunifuTextBox_TenSP.Name = "bunifuTextBox_TenSP";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_TenSP.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox_TenSP.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_TenSP.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_TenSP.OnIdleState = stateProperties20;
            this.bunifuTextBox_TenSP.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox_TenSP.PasswordChar = '\0';
            this.bunifuTextBox_TenSP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox_TenSP.PlaceholderText = "Enter text";
            this.bunifuTextBox_TenSP.ReadOnly = false;
            this.bunifuTextBox_TenSP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox_TenSP.SelectedText = "";
            this.bunifuTextBox_TenSP.SelectionLength = 0;
            this.bunifuTextBox_TenSP.SelectionStart = 0;
            this.bunifuTextBox_TenSP.ShortcutsEnabled = true;
            this.bunifuTextBox_TenSP.Size = new System.Drawing.Size(361, 37);
            this.bunifuTextBox_TenSP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox_TenSP.TabIndex = 1;
            this.bunifuTextBox_TenSP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox_TenSP.TextMarginBottom = 0;
            this.bunifuTextBox_TenSP.TextMarginLeft = 3;
            this.bunifuTextBox_TenSP.TextMarginTop = 0;
            this.bunifuTextBox_TenSP.TextPlaceholder = "Enter text";
            this.bunifuTextBox_TenSP.UseSystemPasswordChar = false;
            this.bunifuTextBox_TenSP.WordWrap = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Thêm";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges7;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(0, 382);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(211, 57);
            this.bunifuButton1.TabIndex = 2;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Xóa";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges8;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(0, 446);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(211, 57);
            this.bunifuButton2.TabIndex = 2;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Mới";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges9;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleBorderRadius = 1;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(0, 318);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(211, 57);
            this.bunifuButton3.TabIndex = 2;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Sửa";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges10;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.IdleBorderRadius = 1;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(0, 510);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.OnDisabledState.BorderRadius = 1;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.BorderRadius = 1;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.BorderRadius = 1;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = null;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.BorderRadius = 1;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(211, 57);
            this.bunifuButton4.TabIndex = 2;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            this.bunifuButton4.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.Controls.Add(this.bunifuButton2);
            this.panel1.Controls.Add(this.bunifuButton4);
            this.panel1.Controls.Add(this.bunifuButton_DanhMuc);
            this.panel1.Controls.Add(this.bunifuButton1);
            this.panel1.Controls.Add(this.bunifuButton3);
            this.panel1.Location = new System.Drawing.Point(882, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(211, 578);
            this.panel1.TabIndex = 3;
            // 
            // bunifuButton_DanhMuc
            // 
            this.bunifuButton_DanhMuc.AllowAnimations = true;
            this.bunifuButton_DanhMuc.AllowMouseEffects = true;
            this.bunifuButton_DanhMuc.AllowToggling = false;
            this.bunifuButton_DanhMuc.AnimationSpeed = 200;
            this.bunifuButton_DanhMuc.AutoGenerateColors = false;
            this.bunifuButton_DanhMuc.AutoRoundBorders = false;
            this.bunifuButton_DanhMuc.AutoSizeLeftIcon = true;
            this.bunifuButton_DanhMuc.AutoSizeRightIcon = true;
            this.bunifuButton_DanhMuc.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton_DanhMuc.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_DanhMuc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton_DanhMuc.BackgroundImage")));
            this.bunifuButton_DanhMuc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_DanhMuc.ButtonText = "Thêm danh mục";
            this.bunifuButton_DanhMuc.ButtonTextMarginLeft = 0;
            this.bunifuButton_DanhMuc.ColorContrastOnClick = 45;
            this.bunifuButton_DanhMuc.ColorContrastOnHover = 45;
            this.bunifuButton_DanhMuc.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.bunifuButton_DanhMuc.CustomizableEdges = borderEdges11;
            this.bunifuButton_DanhMuc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton_DanhMuc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton_DanhMuc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton_DanhMuc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton_DanhMuc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton_DanhMuc.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton_DanhMuc.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_DanhMuc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton_DanhMuc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton_DanhMuc.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton_DanhMuc.IconMarginLeft = 11;
            this.bunifuButton_DanhMuc.IconPadding = 10;
            this.bunifuButton_DanhMuc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton_DanhMuc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton_DanhMuc.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton_DanhMuc.IconSize = 25;
            this.bunifuButton_DanhMuc.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_DanhMuc.IdleBorderRadius = 1;
            this.bunifuButton_DanhMuc.IdleBorderThickness = 1;
            this.bunifuButton_DanhMuc.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_DanhMuc.IdleIconLeftImage = null;
            this.bunifuButton_DanhMuc.IdleIconRightImage = null;
            this.bunifuButton_DanhMuc.IndicateFocus = false;
            this.bunifuButton_DanhMuc.Location = new System.Drawing.Point(0, 12);
            this.bunifuButton_DanhMuc.Name = "bunifuButton_DanhMuc";
            this.bunifuButton_DanhMuc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton_DanhMuc.OnDisabledState.BorderRadius = 1;
            this.bunifuButton_DanhMuc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_DanhMuc.OnDisabledState.BorderThickness = 1;
            this.bunifuButton_DanhMuc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton_DanhMuc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton_DanhMuc.OnDisabledState.IconLeftImage = null;
            this.bunifuButton_DanhMuc.OnDisabledState.IconRightImage = null;
            this.bunifuButton_DanhMuc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton_DanhMuc.onHoverState.BorderRadius = 1;
            this.bunifuButton_DanhMuc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_DanhMuc.onHoverState.BorderThickness = 1;
            this.bunifuButton_DanhMuc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton_DanhMuc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_DanhMuc.onHoverState.IconLeftImage = null;
            this.bunifuButton_DanhMuc.onHoverState.IconRightImage = null;
            this.bunifuButton_DanhMuc.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_DanhMuc.OnIdleState.BorderRadius = 1;
            this.bunifuButton_DanhMuc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_DanhMuc.OnIdleState.BorderThickness = 1;
            this.bunifuButton_DanhMuc.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_DanhMuc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_DanhMuc.OnIdleState.IconLeftImage = null;
            this.bunifuButton_DanhMuc.OnIdleState.IconRightImage = null;
            this.bunifuButton_DanhMuc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton_DanhMuc.OnPressedState.BorderRadius = 1;
            this.bunifuButton_DanhMuc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_DanhMuc.OnPressedState.BorderThickness = 1;
            this.bunifuButton_DanhMuc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton_DanhMuc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_DanhMuc.OnPressedState.IconLeftImage = null;
            this.bunifuButton_DanhMuc.OnPressedState.IconRightImage = null;
            this.bunifuButton_DanhMuc.Size = new System.Drawing.Size(211, 57);
            this.bunifuButton_DanhMuc.TabIndex = 2;
            this.bunifuButton_DanhMuc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton_DanhMuc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton_DanhMuc.TextMarginLeft = 0;
            this.bunifuButton_DanhMuc.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton_DanhMuc.UseDefaultRadiusAndThickness = true;
            this.bunifuButton_DanhMuc.Click += new System.EventHandler(this.bunifuButton_DanhMuc_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(486, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(74, 15);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Tên sản phẩm";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox_Gia
            // 
            this.bunifuTextBox_Gia.AcceptsReturn = false;
            this.bunifuTextBox_Gia.AcceptsTab = false;
            this.bunifuTextBox_Gia.AnimationSpeed = 200;
            this.bunifuTextBox_Gia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox_Gia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox_Gia.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox_Gia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox_Gia.BackgroundImage")));
            this.bunifuTextBox_Gia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox_Gia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox_Gia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox_Gia.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox_Gia.BorderRadius = 1;
            this.bunifuTextBox_Gia.BorderThickness = 1;
            this.bunifuTextBox_Gia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox_Gia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_Gia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox_Gia.DefaultText = "";
            this.bunifuTextBox_Gia.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox_Gia.HideSelection = true;
            this.bunifuTextBox_Gia.IconLeft = null;
            this.bunifuTextBox_Gia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_Gia.IconPadding = 10;
            this.bunifuTextBox_Gia.IconRight = null;
            this.bunifuTextBox_Gia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_Gia.Lines = new string[0];
            this.bunifuTextBox_Gia.Location = new System.Drawing.Point(486, 92);
            this.bunifuTextBox_Gia.MaxLength = 32767;
            this.bunifuTextBox_Gia.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox_Gia.Modified = false;
            this.bunifuTextBox_Gia.Multiline = false;
            this.bunifuTextBox_Gia.Name = "bunifuTextBox_Gia";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_Gia.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox_Gia.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_Gia.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_Gia.OnIdleState = stateProperties24;
            this.bunifuTextBox_Gia.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox_Gia.PasswordChar = '\0';
            this.bunifuTextBox_Gia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox_Gia.PlaceholderText = "Enter text";
            this.bunifuTextBox_Gia.ReadOnly = false;
            this.bunifuTextBox_Gia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox_Gia.SelectedText = "";
            this.bunifuTextBox_Gia.SelectionLength = 0;
            this.bunifuTextBox_Gia.SelectionStart = 0;
            this.bunifuTextBox_Gia.ShortcutsEnabled = true;
            this.bunifuTextBox_Gia.Size = new System.Drawing.Size(361, 37);
            this.bunifuTextBox_Gia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox_Gia.TabIndex = 1;
            this.bunifuTextBox_Gia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox_Gia.TextMarginBottom = 0;
            this.bunifuTextBox_Gia.TextMarginLeft = 3;
            this.bunifuTextBox_Gia.TextMarginTop = 0;
            this.bunifuTextBox_Gia.TextPlaceholder = "Enter text";
            this.bunifuTextBox_Gia.UseSystemPasswordChar = false;
            this.bunifuTextBox_Gia.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(486, 76);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(17, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Giá";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox_MoTa
            // 
            this.bunifuTextBox_MoTa.AcceptsReturn = false;
            this.bunifuTextBox_MoTa.AcceptsTab = false;
            this.bunifuTextBox_MoTa.AnimationSpeed = 200;
            this.bunifuTextBox_MoTa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox_MoTa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox_MoTa.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox_MoTa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox_MoTa.BackgroundImage")));
            this.bunifuTextBox_MoTa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox_MoTa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox_MoTa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox_MoTa.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox_MoTa.BorderRadius = 1;
            this.bunifuTextBox_MoTa.BorderThickness = 1;
            this.bunifuTextBox_MoTa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox_MoTa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_MoTa.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox_MoTa.DefaultText = "";
            this.bunifuTextBox_MoTa.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox_MoTa.HideSelection = true;
            this.bunifuTextBox_MoTa.IconLeft = null;
            this.bunifuTextBox_MoTa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_MoTa.IconPadding = 10;
            this.bunifuTextBox_MoTa.IconRight = null;
            this.bunifuTextBox_MoTa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_MoTa.Lines = new string[0];
            this.bunifuTextBox_MoTa.Location = new System.Drawing.Point(487, 219);
            this.bunifuTextBox_MoTa.MaxLength = 32767;
            this.bunifuTextBox_MoTa.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox_MoTa.Modified = false;
            this.bunifuTextBox_MoTa.Multiline = false;
            this.bunifuTextBox_MoTa.Name = "bunifuTextBox_MoTa";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_MoTa.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox_MoTa.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_MoTa.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_MoTa.OnIdleState = stateProperties28;
            this.bunifuTextBox_MoTa.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox_MoTa.PasswordChar = '\0';
            this.bunifuTextBox_MoTa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox_MoTa.PlaceholderText = "Enter text";
            this.bunifuTextBox_MoTa.ReadOnly = false;
            this.bunifuTextBox_MoTa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox_MoTa.SelectedText = "";
            this.bunifuTextBox_MoTa.SelectionLength = 0;
            this.bunifuTextBox_MoTa.SelectionStart = 0;
            this.bunifuTextBox_MoTa.ShortcutsEnabled = true;
            this.bunifuTextBox_MoTa.Size = new System.Drawing.Size(361, 37);
            this.bunifuTextBox_MoTa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox_MoTa.TabIndex = 1;
            this.bunifuTextBox_MoTa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox_MoTa.TextMarginBottom = 0;
            this.bunifuTextBox_MoTa.TextMarginLeft = 3;
            this.bunifuTextBox_MoTa.TextMarginTop = 0;
            this.bunifuTextBox_MoTa.TextPlaceholder = "Enter text";
            this.bunifuTextBox_MoTa.UseSystemPasswordChar = false;
            this.bunifuTextBox_MoTa.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(486, 204);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(31, 15);
            this.bunifuLabel4.TabIndex = 4;
            this.bunifuLabel4.Text = "Mô tả";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDropdown_DanhMuc
            // 
            this.bunifuDropdown_DanhMuc.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDropdown_DanhMuc.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdown_DanhMuc.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdown_DanhMuc.BorderRadius = 1;
            this.bunifuDropdown_DanhMuc.Color = System.Drawing.Color.Silver;
            this.bunifuDropdown_DanhMuc.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdown_DanhMuc.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown_DanhMuc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdown_DanhMuc.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown_DanhMuc.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdown_DanhMuc.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown_DanhMuc.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdown_DanhMuc.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdown_DanhMuc.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdown_DanhMuc.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown_DanhMuc.FillDropDown = true;
            this.bunifuDropdown_DanhMuc.FillIndicator = false;
            this.bunifuDropdown_DanhMuc.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdown_DanhMuc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDropdown_DanhMuc.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown_DanhMuc.FormattingEnabled = true;
            this.bunifuDropdown_DanhMuc.Icon = null;
            this.bunifuDropdown_DanhMuc.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown_DanhMuc.IndicatorColor = System.Drawing.Color.Gray;
            this.bunifuDropdown_DanhMuc.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown_DanhMuc.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdown_DanhMuc.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdown_DanhMuc.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown_DanhMuc.ItemHeight = 26;
            this.bunifuDropdown_DanhMuc.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDropdown_DanhMuc.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdown_DanhMuc.ItemTopMargin = 3;
            this.bunifuDropdown_DanhMuc.Location = new System.Drawing.Point(547, 268);
            this.bunifuDropdown_DanhMuc.Name = "bunifuDropdown_DanhMuc";
            this.bunifuDropdown_DanhMuc.Size = new System.Drawing.Size(300, 32);
            this.bunifuDropdown_DanhMuc.TabIndex = 5;
            this.bunifuDropdown_DanhMuc.Text = null;
            this.bunifuDropdown_DanhMuc.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown_DanhMuc.TextLeftMargin = 5;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(486, 268);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(55, 15);
            this.bunifuLabel5.TabIndex = 4;
            this.bunifuLabel5.Text = "Danh mục";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox_SL
            // 
            this.bunifuTextBox_SL.AcceptsReturn = false;
            this.bunifuTextBox_SL.AcceptsTab = false;
            this.bunifuTextBox_SL.AnimationSpeed = 200;
            this.bunifuTextBox_SL.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox_SL.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox_SL.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox_SL.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox_SL.BackgroundImage")));
            this.bunifuTextBox_SL.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox_SL.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox_SL.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox_SL.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox_SL.BorderRadius = 1;
            this.bunifuTextBox_SL.BorderThickness = 1;
            this.bunifuTextBox_SL.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox_SL.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_SL.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox_SL.DefaultText = "";
            this.bunifuTextBox_SL.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox_SL.HideSelection = true;
            this.bunifuTextBox_SL.IconLeft = null;
            this.bunifuTextBox_SL.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_SL.IconPadding = 10;
            this.bunifuTextBox_SL.IconRight = null;
            this.bunifuTextBox_SL.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox_SL.Lines = new string[0];
            this.bunifuTextBox_SL.Location = new System.Drawing.Point(486, 155);
            this.bunifuTextBox_SL.MaxLength = 32767;
            this.bunifuTextBox_SL.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox_SL.Modified = false;
            this.bunifuTextBox_SL.Multiline = false;
            this.bunifuTextBox_SL.Name = "bunifuTextBox_SL";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_SL.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox_SL.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_SL.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox_SL.OnIdleState = stateProperties32;
            this.bunifuTextBox_SL.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox_SL.PasswordChar = '\0';
            this.bunifuTextBox_SL.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox_SL.PlaceholderText = "Enter text";
            this.bunifuTextBox_SL.ReadOnly = false;
            this.bunifuTextBox_SL.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox_SL.SelectedText = "";
            this.bunifuTextBox_SL.SelectionLength = 0;
            this.bunifuTextBox_SL.SelectionStart = 0;
            this.bunifuTextBox_SL.ShortcutsEnabled = true;
            this.bunifuTextBox_SL.Size = new System.Drawing.Size(361, 37);
            this.bunifuTextBox_SL.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox_SL.TabIndex = 1;
            this.bunifuTextBox_SL.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox_SL.TextMarginBottom = 0;
            this.bunifuTextBox_SL.TextMarginLeft = 3;
            this.bunifuTextBox_SL.TextMarginTop = 0;
            this.bunifuTextBox_SL.TextPlaceholder = "Enter text";
            this.bunifuTextBox_SL.UseSystemPasswordChar = false;
            this.bunifuTextBox_SL.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(486, 140);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(68, 15);
            this.bunifuLabel6.TabIndex = 4;
            this.bunifuLabel6.Text = "Số lượng tồn";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton_ThemAnh
            // 
            this.bunifuButton_ThemAnh.AllowAnimations = true;
            this.bunifuButton_ThemAnh.AllowMouseEffects = true;
            this.bunifuButton_ThemAnh.AllowToggling = false;
            this.bunifuButton_ThemAnh.AnimationSpeed = 200;
            this.bunifuButton_ThemAnh.AutoGenerateColors = false;
            this.bunifuButton_ThemAnh.AutoRoundBorders = false;
            this.bunifuButton_ThemAnh.AutoSizeLeftIcon = true;
            this.bunifuButton_ThemAnh.AutoSizeRightIcon = true;
            this.bunifuButton_ThemAnh.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton_ThemAnh.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_ThemAnh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton_ThemAnh.BackgroundImage")));
            this.bunifuButton_ThemAnh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_ThemAnh.ButtonText = "Thêm ảnh";
            this.bunifuButton_ThemAnh.ButtonTextMarginLeft = 0;
            this.bunifuButton_ThemAnh.ColorContrastOnClick = 45;
            this.bunifuButton_ThemAnh.ColorContrastOnHover = 45;
            this.bunifuButton_ThemAnh.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.bunifuButton_ThemAnh.CustomizableEdges = borderEdges12;
            this.bunifuButton_ThemAnh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton_ThemAnh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton_ThemAnh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton_ThemAnh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton_ThemAnh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton_ThemAnh.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton_ThemAnh.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_ThemAnh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton_ThemAnh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton_ThemAnh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton_ThemAnh.IconMarginLeft = 11;
            this.bunifuButton_ThemAnh.IconPadding = 10;
            this.bunifuButton_ThemAnh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton_ThemAnh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton_ThemAnh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton_ThemAnh.IconSize = 25;
            this.bunifuButton_ThemAnh.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_ThemAnh.IdleBorderRadius = 1;
            this.bunifuButton_ThemAnh.IdleBorderThickness = 1;
            this.bunifuButton_ThemAnh.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_ThemAnh.IdleIconLeftImage = null;
            this.bunifuButton_ThemAnh.IdleIconRightImage = null;
            this.bunifuButton_ThemAnh.IndicateFocus = false;
            this.bunifuButton_ThemAnh.Location = new System.Drawing.Point(487, 318);
            this.bunifuButton_ThemAnh.Name = "bunifuButton_ThemAnh";
            this.bunifuButton_ThemAnh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton_ThemAnh.OnDisabledState.BorderRadius = 1;
            this.bunifuButton_ThemAnh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_ThemAnh.OnDisabledState.BorderThickness = 1;
            this.bunifuButton_ThemAnh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton_ThemAnh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton_ThemAnh.OnDisabledState.IconLeftImage = null;
            this.bunifuButton_ThemAnh.OnDisabledState.IconRightImage = null;
            this.bunifuButton_ThemAnh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton_ThemAnh.onHoverState.BorderRadius = 1;
            this.bunifuButton_ThemAnh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_ThemAnh.onHoverState.BorderThickness = 1;
            this.bunifuButton_ThemAnh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton_ThemAnh.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_ThemAnh.onHoverState.IconLeftImage = null;
            this.bunifuButton_ThemAnh.onHoverState.IconRightImage = null;
            this.bunifuButton_ThemAnh.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_ThemAnh.OnIdleState.BorderRadius = 1;
            this.bunifuButton_ThemAnh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_ThemAnh.OnIdleState.BorderThickness = 1;
            this.bunifuButton_ThemAnh.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton_ThemAnh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_ThemAnh.OnIdleState.IconLeftImage = null;
            this.bunifuButton_ThemAnh.OnIdleState.IconRightImage = null;
            this.bunifuButton_ThemAnh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton_ThemAnh.OnPressedState.BorderRadius = 1;
            this.bunifuButton_ThemAnh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton_ThemAnh.OnPressedState.BorderThickness = 1;
            this.bunifuButton_ThemAnh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton_ThemAnh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton_ThemAnh.OnPressedState.IconLeftImage = null;
            this.bunifuButton_ThemAnh.OnPressedState.IconRightImage = null;
            this.bunifuButton_ThemAnh.Size = new System.Drawing.Size(84, 29);
            this.bunifuButton_ThemAnh.TabIndex = 6;
            this.bunifuButton_ThemAnh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton_ThemAnh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton_ThemAnh.TextMarginLeft = 0;
            this.bunifuButton_ThemAnh.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton_ThemAnh.UseDefaultRadiusAndThickness = true;
            this.bunifuButton_ThemAnh.Click += new System.EventHandler(this.bunifuButton_ThemAnh_Click);
            // 
            // openFileDialog_SanPham
            // 
            this.openFileDialog_SanPham.FileName = "openFileDialog1";
            // 
            // bunifuPictureBox_SanPham
            // 
            this.bunifuPictureBox_SanPham.AllowFocused = false;
            this.bunifuPictureBox_SanPham.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox_SanPham.AutoSizeHeight = true;
            this.bunifuPictureBox_SanPham.BorderRadius = 0;
            this.bunifuPictureBox_SanPham.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox_SanPham.Image")));
            this.bunifuPictureBox_SanPham.IsCircle = false;
            this.bunifuPictureBox_SanPham.Location = new System.Drawing.Point(577, 306);
            this.bunifuPictureBox_SanPham.Name = "bunifuPictureBox_SanPham";
            this.bunifuPictureBox_SanPham.Size = new System.Drawing.Size(270, 270);
            this.bunifuPictureBox_SanPham.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox_SanPham.TabIndex = 7;
            this.bunifuPictureBox_SanPham.TabStop = false;
            this.bunifuPictureBox_SanPham.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.bunifuPictureBox_SanPham.Click += new System.EventHandler(this.bunifuPictureBox_SanPham_Click);
            // 
            // SanPham_form
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1093, 577);
            this.Controls.Add(this.bunifuPictureBox_SanPham);
            this.Controls.Add(this.bunifuButton_ThemAnh);
            this.Controls.Add(this.bunifuDropdown_DanhMuc);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.bunifuTextBox_SL);
            this.Controls.Add(this.bunifuTextBox_MoTa);
            this.Controls.Add(this.bunifuTextBox_Gia);
            this.Controls.Add(this.bunifuTextBox_TenSP);
            this.Controls.Add(this.bunifuDataGridView_SanPham);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "SanPham_form";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "SanPham_form";
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView_SanPham)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox_SanPham)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView_SanPham;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox_TenSP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton_DanhMuc;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox_Gia;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox_MoTa;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown_DanhMuc;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox_SL;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton_ThemAnh;
        private System.Windows.Forms.OpenFileDialog openFileDialog_SanPham;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox_SanPham;
    }
}